### ISSUE TITLE
Cards/View Design

### ISSUE THREAD

**Issue by mingyaang** [CMPUT301F20T41/boromi#10]
## Description

This task is more demanding in learning new things than #8 since it will likely involve looking up how to use Material Design from Google. The intent is for the developer to create the cards that show small snippets of info that will be inflated into view groups. For more reference material please check out the wiki or the [figma](https://www.figma.com/proto/94WEbiby5hrmILONVx7Vrx/BoRoMi-Design?node-id=47337%3A1239&scaling=scale-down). 

A side note that, although the cards do not need information currently, develop them with the thought that they will later be inflated. Also please use ID/Strings values that make sense. Use a common naming scheme whenever possible.

---

**Deliverable**
- Well designed and functional cards (empty methods for listeners on them should they be required)
- A demo/activity that has the developed cards so they can be reviewed

**Comment by blchelle** [comment]
Is this inclusive of overlays like "Add Book" & "Edit Book" or is it primarily focused on just the cards?

**Comment by mingyaang** [comment]
I'm thinking this is for the actual contents of each window, for now I would say anything that is critical structure should be included. Ex. Making cards to show the books, and adding/editing the books views, and any other cards that are in central workflow of borrowing, returning, lending books.

**Comment by ravioli0509** [comment]
Should we have standards of which design patterns/tool belongs to which functions?
For example, usually snackbars are used for alert/notifications, but we don't want to abuse it by using it for other functions.

**Comment by mingyaang** [comment]
IMO I don't think it's too good to enforce too much since not all of us know the best practices and we are all learning after all. But I trust everyone to use their best judgements when developing stuff, don't just put in code because it works. In the case of something like a toast. Don't display some lengthy information about a book inside a toast, because it will disappear, common sense like that is fine :). Feel free to exercise your own opinion on the matter tho
A little aside: But please use best practices when you can, we all should strive to be using best practices anyway :)
