### ISSUE TITLE
Integration of Cards and Views Into Activities

### ISSUE THREAD

**Issue by mingyaang** [CMPUT301F20T41/boromi#15]
## Description

Uses #8 , #10 
This ticket is meant to be completed once both the activity flows and cards/views are completed. The goal is to meld the two aspects together so that we have an app that looks somewhat like the mockups. This will definitely require coding to inflate views into existence, as well as modifying constraints so they make sense. This will probably also involve shifting around the activity listeners that transition things so everything makes 'sense'.

If everything integrates well, this will be a fairly short ticket. If it doesn't, then it could take a _long while_. Recommend 2 people work on this if it reaches such a place

**Things to consider**
1. Does the app look reasonable on different devices. (RIP)
2. Beware of text overflows - What happens if a book is 5000000 lines long, does it overflow into other views during integration.
3. It may be reasonable to hardcode in some mock cards if no data is available, but make sure to indicate these somehow like a ```//TODO``` flag so they can be changed in the future

---

**Deliverable**
1. An alpha version of the UI

Currently blocked by #8 , #10

**Comment by ravioli0509** [comment]
Integration of controllers are done
