### ISSUE TITLE
Integration of Controllers and UI

### ISSUE THREAD

**Issue by mingyaang** [CMPUT301F20T41/boromi#30]
## Description

This is a **critical ticket**. It needs to be completed before the project deadline. This will somewhat mark the "halfway" point in the project. Currently we have controllers, and the UI has some structure to it. However, now the UI needs to work with the controllers. 
This means :
- Passing parameters from the UI to the Controllers
- Executing controller code when buttons / events occur
- Properly adding callback functions to reflect changes

As with all tickets for project part 3, only critical structure needs to be implemented. There is no need to do anything fancy, it's relatively straight forward. However, integrating things can take a while. 

This ticket is blocked by #15 #17 #27 

---

### Deliverable. 

- Working prototype that can actually be used to request books
- No need for book return functionality
- User's actions reflect the proper workflow

**Comment by ravioli0509** [comment]
Integrations are done, and we are passed the deadline. Will close this now
