### ISSUE TITLE
Book Model Improvement

### ISSUE THREAD

**Issue by blchelle** [CMPUT301F20T41/boromi#31]
## Description
Currently, the book model has bare minimum functionality which causes problems when interacting with firebase.

## Deliverables
1. The type of the bookId field should be changed from UUID to String. Firestore has no clue how to handle the UUID data type and gives a very weird result as seen below.
![image](https://user-images.githubusercontent.com/39068407/97501706-5ed75c80-1937-11eb-8445-30c3c96f4216.png)
2. Remove the attribute ```desc``` since it is not needed for the requirements. Also, remove the getters and setters
3. Add an attribute ```title``` since it is needed for the requirements. Also, add the getters and setters
4. Remove all the existing constructors, you should not be able to construct a book without an owner, isbn, title, author.
5. Add a constructor which takes the following arguments: (owner, isbn, title, author)
6. Add a constructor which takes the following arguments: (owner, isbn, title, author, bookId)
7. Add a constructor which takes the following arguments: (owner, isbn, title, author, status)
8. Add a constructor which takes the following arguments: (owner, isbn, title, author, workflow)
9. Add a constructor which takes the following arguments: (owner, isbn, title, author, status, bookId)
10. Add a constructor which takes the following arguments: (owner, isbn, title, author, workflow, bookId)
11. Add a constructor which takes the following arguments: (owner, isbn, title, author, status,  workflow)
12. Add a constructor which takes the following arguments: (owner, isbn, title, author, status,  workflow, bookId)

**Comment by mingyaang** [comment]
oh haha, please just call UUID.random().toString() when you are constructing the book :) that should fix the issue
