### ISSUE TITLE
Complete Object Oriented Analysis

### ISSUE THREAD

**Issue by blchelle** [CMPUT301F20T41/boromi#4]
## Description
Create a UML Class diagram that documents all the classes, interfaces and relationships which are going to be required for the project requirements and user stories. Upon completion, export the UML Class diagram as a png file and insert your created diagram into the doc folder in the repository

**Specification on eclass**
Document your initial object-oriented analysis using a UML class diagram (or diagrams), focusing on the most important anticipated classes, interfaces, and relationships. Add notes if the purpose of a class, interface, or relationship is likely not clear to an outsider. The diagram(s) will likely evolve.

I estimate this task will require 2-3 people

**Comment by mingyaang** [comment]
Initial drafts for the preparation phase is complete
