### ISSUE TITLE
Missing assets and need info on fonts

### ISSUE THREAD

**Issue by akchen1** [CMPUT301F20T41/boromi#42]
**Deliverable:**
Info on different fonts and sizes
Welcome page - "Welcome to boromi" logo
Auth pages - "back button"
Book tab icon - I see a book icon in the drawables but not sure if its the right one

**Comment by blchelle** [comment]
* I think the back button is already there.
* The book icon currently in the repo is correct, It is different from the one in the prototype but I like it better so I added that.

I did forget the logo though so I'll add that!
