### ISSUE TITLE
Define Firestore Database Schema 

### ISSUE THREAD

**Issue by blchelle** [CMPUT301F20T41/boromi#7]
## Description
Having a well-defined firestore schema is going to be critical to every aspect of our application. It will determine how we write to collections, query for data, update information and delete information (CRUD). This issue will need to be completed before any major development starts.

### Deliverable
This task's deliverable will be a page in our wiki titled "Firestore Schema" that explains the rationale for the decisions. 
* Explain the collections you chose.
* Explain each field for documents in each collection.
* Explain the relationships and give examples of how we will query for data.

### Consider the following
1. What collections should we have?
2. What information (fields) are needed for each document in each collection?
3. How should the collections relate to one another?

### Useful Resources
[Firestore Documentation](https://firebase.google.com/docs/firestore/manage-data/structure-data) ~ 5 mins
[Firestore Youtube Video](https://www.youtube.com/watch?v=haMOUb3KVSo&t) ~ 14 mins
[Firestore Conference](https://www.youtube.com/watch?v=lW7DWV2jST0) ~ 40 mins
[Fireship Youtube Video](https://www.youtube.com/watch?v=35RlydUf6xo) ~ 12 mins

**Comment by mingyaang** [comment]
For the schema it looks good, one thing I think to consider is if we want to store all bookrequests/bookReturns into the db when a user commits that action. But overall I think it's good to close since DB will evolve over time anyway :)
