### ISSUE TITLE
Develop UI/UX Activity Flow

### ISSUE THREAD

**Issue by mingyaang** [CMPUT301F20T41/boromi#8]
### Core business logic

Develop the skeleton structure of the UI/UX workflow for activities as outline in the storyboard. The implementation does not need backend logic, but should allow for transitions between different activities as you will. No need to develop any of the actual view objects, but a small indication of the current page like in the mockup (without the cards) is required. 

For view objects like cards, that will be another related ticket that someone else will work-on, thus this will be a collaborative task in those areas. Another aside note is that, if you know that there should exist logic in this transition: _ex: you press edit book and there should be a dialog that pops up with the EditTextFields, Picture, etc.._, then please add a small ```//TODO``` comment tag, as IDE will highlight the message block.

---

**Deliverable**
- A working prototype that a user can click in and out between the different sections
- Support for various OPs like pressing "back" on the android phone

This issue is a parent to the following:
- [ ] #10 Cards/Views

**Comment by blchelle** [comment]
This sounds like a somewhat long task, maybe 2-3 people should be assigned to this and then work in pairs.

**Comment by mingyaang** [comment]
Yes, I agree 
That's why I think we can correlate this with the person who will create the views for the smaller objects. Such as the cards, layouts, etc. My intent is more for this class to just create empty android activities that respond to transitions, either clicking a button or etc.
